include: package:very_good_analysis/analysis_options.5.1.0.yaml
formatter:
  page_width: 120
  trailing_commas: preserve
linter:
  rules:
    public_member_api_docs: false
    sort_pub_dependencies: false
