include: package:very_good_analysis/analysis_options.8.0.0.yaml
formatter:
  page_width: 120
  trailing_commas: preserve
linter:
  rules:
    lines_longer_than_80_chars: false
    public_member_api_docs: false
    sort_pub_dependencies: false
analyzer:
  exclude:
    - **/*.g.dart
