name: barcodes
description: Showing and saving a list of barcodes
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  
  intl: ^0.18.1
  barcode_widget: ^2.0.4

  flutter_riverpod: ^2.5.1
  logger: ^2.1.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.3.5
  sembast: ^3.7.1
  sembast_web: ^2.3.0
  go_router: ^13.2.1
  
  path_provider: ^2.1.2
  package_info_plus: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  very_good_analysis: ^5.1.0
  flutter_lints: ^3.0.1
  riverpod_lint: ^2.3.10
  custom_lint: ^0.6.4
  build_runner: ^2.4.8
  riverpod_generator: ^2.4.0
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  go_router_builder: ^2.4.1

flutter:
  uses-material-design: true
  generate: true
