name: barcodes
description: Showing and saving a list of barcodes
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  
  intl: ^0.19.0
  barcode_widget: ^2.0.4

  flutter_riverpod: ^2.5.1
  logger: ^2.4.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.3.5
<<<<<<< HEAD
  sembast: ^3.7.5
  sembast_web: ^2.4.0
  go_router: ^13.2.5
  
  path_provider: ^2.1.4
  package_info_plus: ^8.1.0
=======
  sembast: ^3.7.1
  sembast_web: ^2.3.0
  go_router: ^13.2.4
  
  path_provider: ^2.1.3
  package_info_plus: ^6.0.0
>>>>>>> e2dc6b4d192abbbcb105f48c3291f0b9d7fa10f5

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  very_good_analysis: ^5.1.0
  flutter_lints: ^3.0.2
  riverpod_lint: ^2.3.10
  custom_lint: ^0.6.4
  build_runner: ^2.4.13
  riverpod_generator: ^2.4.0
<<<<<<< HEAD
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  go_router_builder: ^2.7.1
=======
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  go_router_builder: ^2.5.1
>>>>>>> e2dc6b4d192abbbcb105f48c3291f0b9d7fa10f5

flutter:
  uses-material-design: true
  generate: true
