name: barcodes
description: Showing and saving a list of barcodes
version: 0.2.0
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  
  intl: ^0.19.0
  barcode_widget: ^2.0.4

  flutter_riverpod: ^2.6.1
  logger: ^2.4.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.6.1
  sembast: ^3.7.5
  sembast_web: ^2.4.0+4
  go_router: ^14.3.0
  
  path_provider: ^2.1.4
  package_info_plus: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  very_good_analysis: ^6.0.0
  flutter_lints: ^5.0.0
  riverpod_lint: ^2.6.1
  custom_lint: ^0.6.8
  build_runner: ^2.4.13
  riverpod_generator: ^2.6.1
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  go_router_builder: ^2.7.1

flutter:
  uses-material-design: true
  generate: true
